version: "3.9"
services:
  pgvector:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    env_file:
      - ./.env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 5s

  couch_server:
    build:
      context: ./couch_server/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5984:5984"
    env_file:
      - ./.env.prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 15s
      timeout: 5s
    volumes:
      - couchdb:/opt/couchdb/data

  ai_service:
    build:
      context: ./ai_service/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      pgvector:
        condition: service_healthy 
    volumes:
      - ./ai_service:/code/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 15s
      timeout: 5s
      retries: 5

  app_gateway:
    build:
      context: ./app_gateway/
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    env_file:
      - ./.env.prod
    depends_on:
      ai_service:
        condition: service_healthy
      couch_server:
        condition: service_healthy
    volumes:
      - ./app_gateway/config:/app/config
      - ./app_gateway/couch:/app/couch
      - ./app_gateway/hooks:/app/hooks
      - ./app_gateway/migrations:/app/migrations
      - pbdata:/app/pb_data

volumes:
  couchdb:
  pbdata:
  pgdata:
