version: "3.9"
services:
  couch_server:
    build:
      context: ./couch_server/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5984:5984"
    env_file:
      - ./.env.prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 15s
      timeout: 2s
      retries: 20
      start_period: 1m

  pgvector:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    env_file:
      - ./.env.prod

  ai_service:
    build:
      context: ./ai_service/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      couch_server:
        condition: service_healthy

  app_gateway:
    build:
      context: ./app_gateway/
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    env_file:
      - ./.env.prod
    depends_on:
      couch_server:
        condition: service_healthy

# volumes:
#   vecdb:
#   couchdb:
#   pbdata:
